<wsdl:definitions name="dbDev" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/StudentServiceBusApplication/StudentSBProject/dbDev" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/StudentServiceBusApplication/StudentSBProject/dbDev" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbDev" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="dbDev_plt">
    <plt:role name="dbDev_role">
      <plt:portType name="tns:dbDev_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbDev" schemaLocation="dbDev.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="dbDevInput_msg">
        <wsdl:part name="dbDevInput_msg" element="db:dbDevInput"/>
    </wsdl:message>
    <wsdl:message name="dbDevOutputCollection_msg">
        <wsdl:part name="dbDevOutputCollection" element="db:dbDevOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbDev_ptt">
        <wsdl:operation name="dbDev">
            <wsdl:input message="tns:dbDevInput_msg"/>
            <wsdl:output message="tns:dbDevOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>